[workspace]
package.version = "0.5.0-pre6"
members = ["crates/*", "bindings/jsonnet", "cmds/*", "tests", "xtask"]
default-members = ["cmds/jrsonnet"]

[workspace.dependencies]
jrsonnet-evaluator = { path = "./crates/jrsonnet-evaluator", version = "0.5.0-pre6" }
jrsonnet-macros = { path = "./crates/jrsonnet-macros", version = "0.5.0-pre6" }
jrsonnet-parser = { path = "./crates/jrsonnet-parser", version = "0.5.0-pre6" }
jrsonnet-interner = { path = "./crates/jrsonnet-interner", version = "0.5.0-pre6" }
jrsonnet-stdlib = { path = "./crates/jrsonnet-stdlib", version = "0.5.0-pre6" }
jrsonnet-cli = { path = "./crates/jrsonnet-cli", version = "0.5.0-pre6" }
jrsonnet-types = { path = "./crates/jrsonnet-types", version = "0.5.0-pre6" }

jrsonnet-gcmodule = "0.3.5"

#[profile.test]
#opt-level = 1

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = 0
panic = "abort"
strip = true

[profile.releasedebug]
inherits = "release"
debug = 2
panic = "unwind"
strip = false
